### ISSUE TITLE
Errors unpacking image are not shown

### ISSUE THREAD

**Issue by matthijskooijman** [torizon/torizoncore-builder#10]
As part of the build process, an existing tarball is unpacked. If this fails, because the file is corrupt, does not exist, or is not otherwise available (in this case the file is outside of the project root, so not available in the docker container without additional docker options), an exception is shown but without stdout/stderr output from the tar/cat command that would help diagnose the issue:

```
Traceback (most recent call last):
  File "/builder/torizoncore-builder", line 221, in <module>
    mainargs.func(mainargs)
  File "/builder/tcbuilder/cli/build.py", line 479, in do_build
    build(args.config_fname, args.storage_directory,
  File "/builder/tcbuilder/cli/build.py", line 446, in build
    handle_input_section(config["input"], storage_dir=storage_dir)
  File "/builder/tcbuilder/cli/build.py", line 98, in handle_input_section
    handle_easy_installer_input(props["easy-installer"], **kwargs)
  File "/builder/tcbuilder/cli/build.py", line 119, in handle_easy_installer_input
    images_cli.images_unpack(
  File "/builder/tcbuilder/cli/images.py", line 139, in images_unpack
    images.import_local_image(image_dir, dir_list[0], dir_list[1], dir_list[2])
  File "/builder/tcbuilder/backend/images.py", line 282, in import_local_image
    subprocess.check_output(tarcmd, shell=True, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cat /home/matthijs/docs/MKIT/3Devo/FM23/yocto-workdir/torizon/build-torizon/deploy/images/verdin-imx8mp/torizon-core-docker-verdin-imx8mp-Tezi_6.5.0-devel-20231127143231+build.0.tar | cat | tar -xf - -C /storage/tezi.tmp' returned non-zero exit status 2.
```

The relevant python code is here: https://github.com/toradex/torizoncore-builder/blob/5ac80ac541c19d5faf834ac9271fc5553f25e0ad/tcbuilder/backend/images.py#L282

This captures stdout, redirects stderr to stdout but then discards the output. I would suggest either not capturing output at all (just let everything print to the terminal by default), or alternatively use a non-check method so output and exist status can be captured separately and then print the output only if the command failed.

I also wonder why the commandline itself is so complicated with two cat calls and one tar in a pipeline that could, AFAICS, be just a single tar command. The current command is also "vulnerable" to shell injection from the filename (which is not so much a security problem, but will break if the filename to the tarball to unpack contains spaces or special characters). This would also be easy to fix if no shell was required to execute the command (but just a single tar command whose arguments could be specified as a list instead of a single string).

**Comment by matthijskooijman** [comment]
Somewhat off-topic, but something to maybe investigate at the same time: When the path to the tar filename contains spaces, the command fails (with exit code 2, but due to lack of error messages I am not sure what fails exactly). From the looks of it the filename is quoted [here](https://github.com/toradex/torizoncore-builder/blob/d1e7528adc163180333ee0686a9df5190dc8f852/tcbuilder/backend/images.py#L237) but not [here](https://github.com/toradex/torizoncore-builder/blob/d1e7528adc163180333ee0686a9df5190dc8f852/tcbuilder/backend/images.py#L279). Also note that just putting quotes around the placeholder is not enough, since then a path containing a single quote still breaks things. Ideally this would be rewritten to run just a single command instead of a pipeline, so no shell evaluation is needed and the arguments to the command can be specified as an array without any word splitting and other interpretation of special characters needed.

**Comment by matthijskooijman** [comment]
> This captures stdout, redirects stderr to stdout but then discards the output.

Turns out that the output is actually stored in the `CalledProcessError` that is raised, so the fix for this was quite easy: Just catch that exception and print the included output. I've implemented this locally, I'll submit that in a PR along with some other changes soon.

**Comment by matthijskooijman** [comment]
> I've implemented this locally, I'll submit that in a PR along with some other changes soon.

Done: #12 

> Somewhat off-topic, but something to maybe investigate at the same time: When the path to the tar filename contains spaces, the command fails

I've also submitted a fix for this (in all subprocess invocations, not just the one I pointed out) in #14.

**Comment by leograba** [comment]
Thanks for the contributions. We'll review and merge them soon.
