### ISSUE TITLE
Feature request: Add bc binary to torizoncore-builder

### ISSUE THREAD

**Issue by lzaugg** [torizon/torizoncore-builder#5]
Hi,

The `torizoncore-builder` image gives a really nice dev experience for everything around the TorizonCore image management (including the cross compilation and toolchain handling). Thanks a lot for that!

Recently we stumbled upon a missing binary in the `torizoncore-builder` image.

**Feature Request:**

Add the `bc` tool (https://packages.debian.org/bullseye/bc) to the torizoncore-builder image

**Reason:**

Because we need to include a linux kernel module which is in-tree but not enabled as module in TorizonCore 5.7, we're compiling/including it as an external kernel module with our own Makefile (as described in https://developer.toradex.com/torizon/os-customization/use-cases/building-external-kernel-modules-with-torizon/). Before using any of those in-tree module sources, certain make targets should be called within the linux kernel source directory, like `prepare`. Unfortunately, `prepare` requires the `bc` binary and so the module build fails (when adding `bc` manually to the image, everything goes well).

I can create a PR if it helps (and this request makes sense).

With our setup and `bc` included in `torizoncore-builder` it seems like one can add even an in-tree kernel module easily if it is not enabled by Torizon.

Best regards,

Lukas

**Comment by leograba** [comment]
Hi @lzaugg, at first it seems ok to add `bc`. I'll check with the TCB developers and get back to you.

By the way, we're happy to enable in-tree modules and kernel configuration in TorizonCore, as long they don't have an overall negative impact on the distribution. That way, you wouldn't need to keep building it with the out-of-tree workflow. If that is an option for you, please request the exact config you need to be enabled in our community. Here is one example of a post requesting a config to be added: https://community.toradex.com/t/enable-ksz8794-in-torizoncore-kernel/19158

**Comment by lzaugg** [comment]
Thanks for your response.

I've already requested the kernel change (https://community.toradex.com/t/enable-config-mmc-vub300-in-torizoncore-kernel/19099), but we're on 5.7 LTS (only patches allowed, obviously). We keep it that way until 6.x can be considered as stable (quartely) for the imx8qxp (.. and we're ready to migrate).

Btw, really great support (community page and here). 
Looking forward.

**Comment by leograba** [comment]
Understood. Indeed, for 5.7 LTS you'd have to go that way.

The developers are ok with adding `bc`, would you please submit the PR? Once it's available, I'll assign it for review.

In the future, we have plans to make the community contribution process for TCB more transparent and straightforward. Knowing there are people interested in contributing helps me drive this process. I'm also happy you enjoy our support, thanks for sharing, and we're looking forward to continuously improving and making the lives of devs always easier.

**Comment by lzaugg** [comment]
PR: https://github.com/toradex/torizoncore-builder/pull/6

**Comment by lzaugg** [comment]
PR got cherry-picked and is on main now 🎉.

**Comment by Nathan-ma** [comment]
@leograba, could we link this issue with its respective PR?
