### ISSUE TITLE
`platform lockbox` fails for non-host network

### ISSUE THREAD

**Issue by lzaugg** [torizon/torizoncore-builder#8]
Because we're using GH Actions for our CI/CD, the docker network cannot be set when using torizoncore-builder.

**Setup**

- torizoncore-builder 3.7.0 (docker)
- running on GH Actions on Ubuntu (but it's the same on my machine, Mac OS X)

**Issue**

Everything works fine so far without `network=host`, including the `bundle` command, but NOT `platform lockbox`. 
The command we run (ids/creds removed):

```bash
docker run --rm -v /deploy -v /home/runner/work/some-project/some-project/image:/workdir -v storage_some-project:/storage -v /var/run/docker.sock:/var/run/docker.sock torizon/torizoncore-builder:3.7.0 platform lockbox --credentials=.credentials.zip --platform linux/arm64 --login-to some-registry.dkr.ecr.eu-central-2.amazonaws.com AWS eySomeCreds --output-directory cache/some-project-lb-combined-v0.1.13 some-project-combined
```

The error when doing a `platform lockbox` is eventually:

```bash
Starting DIND container
Using Docker host "tcp://127.0.0.1:22376"
Connecting to Docker Daemon at "tcp://127.0.0.1:22376"
Stopping DIND container
Removing output directory 'cache/some-project-lb-combined-v0.1.13' due to errors
An unexpected Exception occured. Please provide the following stack trace to
the Toradex TorizonCore support team:


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

After some deep dive into torizoncore-builder, I've seen that for a `bundle` command the dind manager is started with the network param from `get_own_network()`. See 
https://github.com/toradex/torizoncore-builder/blob/1c44b8f9fb1013179427abc559bbb5716fc72bc5/tcbuilder/backend/bundle.py#L553

... while the `platform lockbox` is set to "host" statically. See 

https://github.com/toradex/torizoncore-builder/blob/1c44b8f9fb1013179427abc559bbb5716fc72bc5/tcbuilder/backend/platform.py#L603

After changing the code for starting the dind manager to use the same network setup for `build` and `lockbox platform`, everything is going through; see https://github.com/lzaugg/torizoncore-builder/commit/4f2df1fd5d07b7f85a01cd15c224907f10ecc67c 

Not sure about any side effects, though.

What do you think? File a PR or did I just didn't get it right?

Thanks in advance for any guidance.
Lukas

**Comment by leograba** [comment]
Hi @lzaugg,

Your question was brought up to the TorizonCore Builder developers. We'll let you know about your proposal as soon as possible.

Regards,
Leo

**Comment by leograba** [comment]
It seems your solution is a potential one, indeed.

Please see https://github.com/toradex/torizoncore-builder/commit/836f0e4c91d84dcff4e01bf338a1d601cb3cfc96, which fixed the issue of `bundle` not working on Windows due to a network issue, similar as reported by you for the `platform lockbox`.

We'll gladly review a PR. Once you open it, one of the TCB developers will help review and accept it.

**Comment by lzaugg** [comment]
Hi @leograba , @Nathan-ma 

PR https://github.com/toradex/torizoncore-builder/pull/9 is ready from my side. Please let me know if something is missing.

Regards,
Lukas

**Comment by leograba** [comment]
Thank you, Lukas! Nathan will review the PR.

**Comment by Nathan-ma** [comment]
@lzaugg , Once again, Thank you for the contribution, I am sorry for messing up with the PR, but your contribution is merged.

Manually closing the issue here.
